# -*- coding: utf-8 -*-
# This file was generated by Tkinter Designer by Parth Jadhav
# Clean GUI template with functional click placeholders

from pathlib import Path
import ctypes
import sys
from tkinter import (
    Tk,
    Canvas,
    Entry,
    Label,
    PhotoImage,
    Button,
    END
)

try:
    from PIL import Image, ImageTk
except ImportError:
    Image = None
    ImageTk = None


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\frame0")
THEME = ""
IMAGE_REFS = []


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def load_photo_image(path: str):
    try:
        image = PhotoImage(file=path)
    except Exception:
        if Image is None or ImageTk is None:
            raise
        image = ImageTk.PhotoImage(Image.open(path))
    IMAGE_REFS.append(image)
    return image


def enable_dpi_awareness():
    if sys.platform != "win32":
        return
    try:
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except Exception:
        try:
            ctypes.windll.user32.SetProcessDPIAware()
        except Exception:
            pass


def center_window(window, width, height):
    window.update_idletasks()
    x = int((window.winfo_screenwidth() - width) / 2)
    y = int((window.winfo_screenheight() - height) / 2)
    window.geometry(f"{width}x{height}+{x}+{y}")

# ==========================================
#              GUI INITIALIZATION
# ==========================================
enable_dpi_awareness()

window = Tk()
window.title("Word Guessing Game")
window.geometry("1052x840")
window.configure(bg="#FFFFFF")
center_window(window, 1052, 840)

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=840,
    width=1052,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)
canvas.place(x=0, y=0)

image_image_1 = load_photo_image(relative_to_assets("element_1.png"))
image_1 = canvas.create_image(526.0, 420.0, image=image_image_1)

# --- GUESS LETTER BUTTON ---
canvas.create_rectangle(
    387.0, 697.0, 667.0, 774.0,
    fill="#000000", outline="", tags="guess_btn"
)
canvas.create_text(
    423.0, 711.0, anchor="nw",
    text="Guess Letter", fill="#FFFFFF",
    font=("Roboto", 36 * -1, "normal", "roman"), tags="guess_btn"
)
canvas.tag_bind("guess_btn", "<Button-1>", lambda event: make_a_guess())


# --- ATTEMPTS REMAINING LABEL ---
canvas.create_text(
    403.0, 209.0, anchor="nw",
    text="Attempts Remaining:",
    fill="#1E1E1E", font=("Inter", 24 * -1, "bold", "roman")
)

# --- TEXT ENTRY BOX ---
entry_image_1 = load_photo_image(relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(527.5, 314.5, image=entry_image_1)
entry_1 = Entry(
    window, bd=0, bg="#E0D9D9", fg="#000716",
    insertbackground="#000716", highlightthickness=0,
    font=("Roboto", 28), justify="center"
)
entry_1.place(x=476.0, y=271.0, width=103.0, height=85.0)


# --- ON-SCREEN KEYBOARD KEYS ---

# ROW 1
canvas.create_rectangle(104.0, 396.0, 181.0, 472.0, fill="#FFFBEB", outline="", tags="key_Q")
canvas.create_text(133.86, 418.0, anchor="nw", text="Q", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_Q")
canvas.tag_bind("key_Q", "<Button-1>", lambda e: on_key_click("Q"))

canvas.create_rectangle(191.27, 396.0, 268.27, 472.0, fill="#FFFBEB", outline="", tags="key_W")
canvas.create_text(218.36, 418.0, anchor="nw", text="W", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_W")
canvas.tag_bind("key_W", "<Button-1>", lambda e: on_key_click("W"))

canvas.create_rectangle(278.55, 396.0, 355.55, 472.0, fill="#FFFBEB", outline="", tags="key_E")
canvas.create_text(309.36, 418.0, anchor="nw", text="E", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_E")
canvas.tag_bind("key_E", "<Button-1>", lambda e: on_key_click("E"))

canvas.create_rectangle(364.83, 396.0, 441.83, 472.0, fill="#FFFBEB", outline="", tags="key_R")
canvas.create_text(395.86, 418.0, anchor="nw", text="R", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_R")
canvas.tag_bind("key_R", "<Button-1>", lambda e: on_key_click("R"))

canvas.create_rectangle(452.11, 396.0, 529.11, 472.0, fill="#FFFBEB", outline="", tags="key_T")
canvas.create_text(482.86, 418.0, anchor="nw", text="T", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_T")
canvas.tag_bind("key_T", "<Button-1>", lambda e: on_key_click("T"))

canvas.create_rectangle(539.39, 396.0, 616.39, 472.0, fill="#FFFBEB", outline="", tags="key_Y")
canvas.create_text(569.86, 418.0, anchor="nw", text="Y", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_Y")
canvas.tag_bind("key_Y", "<Button-1>", lambda e: on_key_click("Y"))

canvas.create_rectangle(626.67, 396.0, 703.67, 472.0, fill="#FFFBEB", outline="", tags="key_U")
canvas.create_text(656.36, 418.0, anchor="nw", text="U", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_U")
canvas.tag_bind("key_U", "<Button-1>", lambda e: on_key_click("U"))

canvas.create_rectangle(712.95, 396.0, 789.95, 472.0, fill="#FFFBEB", outline="", tags="key_I")
canvas.create_text(747.86, 418.0, anchor="nw", text="I", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_I")
canvas.tag_bind("key_I", "<Button-1>", lambda e: on_key_click("I"))

canvas.create_rectangle(800.23, 396.0, 877.23, 472.0, fill="#FFFBEB", outline="", tags="key_O")
canvas.create_text(829.86, 418.0, anchor="nw", text="O", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_O")
canvas.tag_bind("key_O", "<Button-1>", lambda e: on_key_click("O"))

canvas.create_rectangle(887.51, 396.0, 964.51, 472.0, fill="#FFFBEB", outline="", tags="key_P")
canvas.create_text(917.36, 418.0, anchor="nw", text="P", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_P")
canvas.tag_bind("key_P", "<Button-1>", lambda e: on_key_click("P"))

# ROW 2
canvas.create_rectangle(143.0, 490.0, 220.0, 566.0, fill="#FFFBEB", outline="", tags="key_A")
canvas.create_text(173.36, 512.0, anchor="nw", text="A", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_A")
canvas.tag_bind("key_A", "<Button-1>", lambda e: on_key_click("A"))

canvas.create_rectangle(229.0, 490.0, 306.0, 566.0, fill="#FFFBEB", outline="", tags="key_S")
canvas.create_text(259.58, 512.0, anchor="nw", text="S", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_S")
canvas.tag_bind("key_S", "<Button-1>", lambda e: on_key_click("S"))

canvas.create_rectangle(315.0, 490.0, 392.0, 566.0, fill="#FFFBEB", outline="", tags="key_D")
canvas.create_text(344.80, 512.0, anchor="nw", text="D", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_D")
canvas.tag_bind("key_D", "<Button-1>", lambda e: on_key_click("D"))

canvas.create_rectangle(400.0, 490.0, 477.0, 566.0, fill="#FFFBEB", outline="", tags="key_F")
canvas.create_text(431.52, 512.0, anchor="nw", text="F", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_F")
canvas.tag_bind("key_F", "<Button-1>", lambda e: on_key_click("F"))

canvas.create_rectangle(486.0, 490.0, 563.0, 566.0, fill="#FFFBEB", outline="", tags="key_G")
canvas.create_text(515.74, 512.0, anchor="nw", text="G", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_G")
canvas.tag_bind("key_G", "<Button-1>", lambda e: on_key_click("G"))

canvas.create_rectangle(572.0, 490.0, 649.0, 566.0, fill="#FFFBEB", outline="", tags="key_H")
canvas.create_text(600.96, 512.0, anchor="nw", text="H", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_H")
canvas.tag_bind("key_H", "<Button-1>", lambda e: on_key_click("H"))

canvas.create_rectangle(658.0, 490.0, 735.0, 566.0, fill="#FFFBEB", outline="", tags="key_J")
canvas.create_text(688.68, 512.0, anchor="nw", text="J", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_J")
canvas.tag_bind("key_J", "<Button-1>", lambda e: on_key_click("J"))

canvas.create_rectangle(743.0, 490.0, 820.0, 566.0, fill="#FFFBEB", outline="", tags="key_K")
canvas.create_text(773.40, 512.0, anchor="nw", text="K", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_K")
canvas.tag_bind("key_K", "<Button-1>", lambda e: on_key_click("K"))

canvas.create_rectangle(829.0, 490.0, 906.0, 566.0, fill="#FFFBEB", outline="", tags="key_L")
canvas.create_text(860.62, 512.0, anchor="nw", text="L", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_L")
canvas.tag_bind("key_L", "<Button-1>", lambda e: on_key_click("L"))

# ROW 3
canvas.create_rectangle(229.0, 584.0, 306.0, 660.0, fill="#FFFBEB", outline="", tags="key_Z")
canvas.create_text(259.58, 606.0, anchor="nw", text="Z", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_Z")
canvas.tag_bind("key_Z", "<Button-1>", lambda e: on_key_click("Z"))

canvas.create_rectangle(315.0, 584.0, 392.0, 660.0, fill="#FFFBEB", outline="", tags="key_X")
canvas.create_text(344.80, 606.0, anchor="nw", text="X", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_X")
canvas.tag_bind("key_X", "<Button-1>", lambda e: on_key_click("X"))

canvas.create_rectangle(400.0, 584.0, 477.0, 660.0, fill="#FFFBEB", outline="", tags="key_C")
canvas.create_text(430.52, 606.0, anchor="nw", text="C", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_C")
canvas.tag_bind("key_C", "<Button-1>", lambda e: on_key_click("C"))

canvas.create_rectangle(486.0, 584.0, 563.0, 660.0, fill="#FFFBEB", outline="", tags="key_V")
canvas.create_text(516.24, 606.0, anchor="nw", text="V", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_V")
canvas.tag_bind("key_V", "<Button-1>", lambda e: on_key_click("V"))

canvas.create_rectangle(572.0, 584.0, 649.0, 660.0, fill="#FFFBEB", outline="", tags="key_B")
canvas.create_text(602.46, 606.0, anchor="nw", text="B", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_B")
canvas.tag_bind("key_B", "<Button-1>", lambda e: on_key_click("B"))

canvas.create_rectangle(658.0, 584.0, 735.0, 660.0, fill="#FFFBEB", outline="", tags="key_N")
canvas.create_text(686.68, 606.0, anchor="nw", text="N", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_N")
canvas.tag_bind("key_N", "<Button-1>", lambda e: on_key_click("N"))

canvas.create_rectangle(743.0, 584.0, 820.0, 660.0, fill="#FFFBEB", outline="", tags="key_M")
canvas.create_text(770.90, 606.0, anchor="nw", text="M", fill="#1E1E1E", font=("Roboto", 24 * -1), tags="key_M")
canvas.tag_bind("key_M", "<Button-1>", lambda e: on_key_click("M"))


# --- SECRET WORD DISPLAY ---
canvas.create_text(
    143.0,
    82.0,
    anchor="nw",
    text="__   __   __   __   __",
    fill="#000000",
    font=("Roboto", 80 * -1, "normal", "roman")
)

window.resizable(False, False)

if __name__ == "__main__":
    window.mainloop()